### ISSUE TITLE
Errors when attempting to use 'run_all.R' script

### ISSUE THREAD

**Issue by chrispmad** [bcgov/ghg-emissions-indicator#13]
Library and source commands worked properly, and all expected output from the three separate scripts (load, clean and output) was generated. 

However, line 22, in which we attempt rmarkdown::render("print_ver/ghg.Rmd",output_file = outfile) returned this error:
Error in loadNamespace(x): there is not package called 'envreportutils.internal'

I have installed and successfully loaded the envreportutils package... not sure about this 'envreportutils.internal'

Also, trying to run line 24 (extrafont::embed_fonts(file.path("print_ver/", outfile)) returned this error:
Error in embedFonts(file = file, format = format, outfile = outfile, options = paste(paste("-I", : GhostScript was not found

**Comment by stephhazlitt** [comment]
{envreportutils.internal} is an internal R package that houses the PDF template (with logos), so Pandoc cannot find this `https://github.com/bcgov/ghg-emissions-indicator/blob/master/print_ver/ghg.Rmd#L5`. You can comment out the `envreportutils.internal::print_ver` and it should render. And then ask colleagues where/how to install the internal template package.

**Comment by chrispmad** [comment]
Thank you so much, Steph!
